baseImageOverrides:
  # TODO(jasonhall): Use build-base in the build-pipeline path, when it's build/released.
  github.com/tektoncd/pipeline/cmd/creds-init: gcr.io/knative-nightly/github.com/knative/build/build-base:latest
  github.com/tektoncd/pipeline/cmd/git-init: gcr.io/knative-nightly/github.com/knative/build/build-base:latest
  github.com/tektoncd/pipeline/cmd/bash: busybox # image should have shell in $PATH
  github.com/tektoncd/pipeline/cmd/entrypoint: busybox # image should have shell in $PATH
  github.com/tektoncd/pipeline/cmd/gsutil: google/cloud-sdk:alpine # image should have gsutil in $PATH
