apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: home-is-set-
spec:
  taskSpec:
    steps:
    - image: public.ecr.aws/ubuntu/ubuntu:latest
      script: |
        #!/usr/bin/env bash
        [[ $HOME == /tekton/home ]]
